### ISSUE TITLE
生成了错误的侧边栏

### ISSUE THREAD

**Issue by NorthCityChen** [luciozhang/vitepress-plugin-autobar#2]
我有一个如下的目录结构：

![image](https://user-images.githubusercontent.com/53619621/206830504-fee09665-a9aa-4de4-9f72-bfe4455234d9.png)

我是这样编写的 `.vitepress/config.js`

```js
import { getSideBar } from "vitepress-plugin-autobar"

module.exports = {
    title: 'Hello VitePress 233',
    description: 'Just playing around.',
    themeConfig: {
        sidebar: getSideBar("./docs"),
    },
}
```

但是 `vitepress-plugin-autobar` 并没有生成正确的目录

```js
vitepress v1.0.0-draft.8
sidebar is create: [{"text":"Child 1 Test","items":[{"text":"Child 1 Test","link":"01.Child-1/test"}]},{"text":"Child 1 Test 2","items":[{"text":"Child 1 Test 2","link":"01.Child-1/test2"}]},{"text":"Child 2 Test","items":[{"text":"Child 2 Test","link":"02.Child-2/test"}]},{"text":"Child 2 Test 2","items":[{"text":"Child 2 Test 2","link":"02.Child-2/test2"}]},{"text":"Index","items":[{"text":"Index","link":"index"}]}]
```

我的环境：

```shell
PS D:\code\vitepress\test> yarn -v
3.3.0
```

```shell
PS D:\code\vitepress\test> node -v
v16.15.1
```

```
"vitepress-plugin-autobar@npm:^1.0.8":
  version: 1.0.8
  resolution: "vitepress-plugin-autobar@npm:1.0.8"
  dependencies:
    glob: ^8.0.3
    lodash: ^4.17.21
  checksum: 6a2d77cb2acd93646b09dce9bba7a6c4c5dfced4cb01032d8251519c8212975de7aed752bd9bb656effbdce6632bc6625fafa36a80ad05c3c8b13f43ae80e9e2
  languageName: node
  linkType: hard
```
